//! FlexSPI NOR Storage Bus Driver module for the NXP RT6xx family of microcontrollers
//!
use core::future::poll_fn;
use core::task::Poll;

use cortex_m::asm;
use embassy_hal_internal::Peripheral;
use mimxrt600_fcb::FlexSpiLutOpcode;
use mimxrt600_fcb::FlexSpiLutOpcode::*;
use storage_bus::storage_bus::{
    AsyncNorStorageBusDriver, BlockingNorStorageBusDriver, DummyCycles, NorStorageBusWidth, NorStorageCmd,
    NorStorageCmdMode, NorStorageCmdType, StorageBusError,
};

use crate::clocks::enable_and_reset;
// use crate::flexspi::errors::FlashError;
use crate::interrupt;
use crate::iopctl::IopctlPin as Pin;
use crate::peripherals;

macro_rules! align {
    ($val:expr, $align:expr) => {
        (($val + $align - 1) / $align) * $align
    };
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI Port Enum.
pub enum FlexSpiFlashPort {
    /// FlexSPI Port A
    PortA,
    /// FlexSPI Port B
    PortB,
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI Flash Port Device Instance Enum.
pub enum FlexSpiFlashPortDeviceInstance {
    /// Device Instance 0
    DeviceInstance0,
    /// Device Instance 1
    DeviceInstance1,
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI Bus Width Enum.
pub enum FlexSpiBusWidth {
    /// Single bit bus width
    Single,
    /// Dual bit bus width
    Dual,
    /// Quad bit bus width
    Quad,
    /// Octal bit bus width
    Octal,
}

impl From<FlexSpiBusWidth> for u8 {
    fn from(bus_width: FlexSpiBusWidth) -> u8 {
        match bus_width {
            FlexSpiBusWidth::Single => 1,
            FlexSpiBusWidth::Dual => 2,
            FlexSpiBusWidth::Quad => 4,
            FlexSpiBusWidth::Octal => 8,
        }
    }
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI Chip Select Interval unit Enum.
pub enum FlexspiCsIntervalCycleUnit {
    /// CS interval unit is 1 cycle
    CsIntervalUnit1Cycle,
    /// CS interval unit is 256 cycle
    CsIntervalUnit256Cycle,
}
#[derive(Clone, Copy, Debug)]
/// FlexSPI AHB Write Wait unit Enum.
pub enum FlexspiAhbWriteWaitUnit {
    /// AWRWAIT unit is 2 ahb clock cycle
    FlexspiAhbWriteWaitUnit2ahbCycle,
    /// AWRWAIT unit is 8 ahb clock cycle.
    FlexspiAhbWriteWaitUnit8ahbCycle,
    /// AWRWAIT unit is 32 ahb clock cycle.
    FlexspiAhbWriteWaitUnit32ahbCycle,
    /// AWRWAIT unit is 128 ahb clock cycle.   
    FlexspiAhbWriteWaitUnit128ahbCycle,
    /// AWRWAIT unit is 512 ahb clock cycle.   
    FlexspiAhbWriteWaitUnit512ahbCycle,
    /// AWRWAIT unit is 2048 ahb clock cycle.  
    FlexspiAhbWriteWaitUnit2048ahbCycle,
    /// AWRWAIT unit is 8192 ahb clock cycle.  
    FlexspiAhbWriteWaitUnit8192ahbCycle,
    /// AWRWAIT unit is 32768 ahb clock cycle.
    FlexspiAhbWriteWaitUnit32768ahbCycle,
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI Read Sample Clock Enum.
pub enum FlexspiReadSampleClock {
    /// Dummy Read strobe generated by FlexSPI self.flexspi_ref and loopback internally
    FlexspiReadSampleClkLoopbackInternally,
    /// Dummy Read strobe generated by FlexSPI self.flexspi_ref and loopback from DQS pad
    FlexspiReadSampleClkLoopbackFromDqsPad,
    /// SCK output clock and loopback from SCK pad
    FlexspiReadSampleClkLoopbackFromSckPad,
    /// Flash provided Read strobe and input from DQS pad
    FlexspiReadSampleClkExternalInputFromDqsPad,
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI AHB Buffer Configuration structure
pub struct FlexspiAhbBufferConfig {
    /// This priority for AHB Master Read which this AHB RX Buffer is assigned.
    pub priority: u8,
    /// AHB Master ID the AHB RX Buffer is assigned.       
    pub master_index: u8,
    /// AHB buffer size in byte.   
    pub buffer_size: u16,
    /// AHB Read Prefetch Enable for current AHB RX Buffer corresponding Master, allows to prefetch data for AHB read access.
    pub enable_prefetch: bool,
}

#[derive(Clone, Copy, Debug)]
/// Flash Device configuration
pub struct FlexspiDeviceConfig {
    /// FLEXSPI serial root clock
    pub flexspi_root_clk: u32,
    /// FLEXSPI use SCK2
    pub is_sck2_enabled: bool,
    /// Flash size in KByte
    pub flash_size_kb: u32,
    /// CS interval unit, 1 or 256 cycle
    pub cs_interval_unit: FlexspiCsIntervalCycleUnit,
    /// CS line assert interval, multiply CS interval unit to get the CS line assert interval cycles
    pub cs_interval: u16,
    /// CS line hold time
    pub cs_hold_time: u8,
    /// CS line setup time
    pub cs_setup_time: u8,
    /// Data valid time for external device                          
    pub data_valid_time: u8,
    /// Column space size                       
    pub columnspace: u8,
    /// If enable word address                        
    pub enable_word_address: bool,
    /// Sequence ID for AHB write command                    
    pub awr_seq_index: u8,
    /// Sequence number for AHB write command
    pub awr_seq_number: u8,
    /// Sequence ID for AHB read command                       
    pub ard_seq_index: u8,
    /// Sequence number for AHB read command
    pub ard_seq_number: u8,
    /// AHB write wait unit
    pub ahb_write_wait_unit: FlexspiAhbWriteWaitUnit,
    /// AHB write wait interval, multiply AHB write interval unit to get the AHB write wait cycles
    pub ahb_write_wait_interval: u16,
    /// Enable/Disable FLEXSPI drive DQS pin as write mask
    pub enable_write_mask: bool,
}

#[derive(Clone, Copy, Debug)]
/// AHB configuration structure
pub struct AhbConfig {
    /// Enable AHB bus write access to IP TX FIFO.
    pub enable_ahb_write_ip_tx_fifo: bool,
    /// Enable AHB bus write access to IP RX FIFO.
    pub enable_ahb_write_ip_rx_fifo: bool,
    /// Timeout wait cycle for AHB command grant, timeout after ahbGrantTimeoutCyle*1024 AHB clock cycles.
    pub ahb_grant_timeout_cycle: u8,
    /// Timeout wait cycle for AHB read/write access, timeout after ahbBusTimeoutCycle*1024 AHB clock cycles.
    pub ahb_bus_timeout_cycle: u16,
    /// Wait cycle for idle state before suspended command sequence resume, timeout after ahbBusTimeoutCycle AHB clock cycles.
    pub resume_wait_cycle: u8,
    /// AHB buffer size.
    pub buffer: [FlexspiAhbBufferConfig; 8],
    /// Enable/disable automatically clean AHB RX Buffer and TX Buffer when FLEXSPI returns STOP mode ACK.
    pub enable_clear_ahb_buffer_opt: bool,
    /// Enable/disable remove AHB read burst start address alignment limitation. when enable, there is no AHB read burst start address alignment limitation.
    pub enable_read_address_opt: bool,
    /// Enable/disable AHB read prefetch feature, when enabled, FLEXSPI will fetch more data than current AHB burst.
    pub enable_ahb_prefetch: bool,
    /// Enable/disable AHB bufferable write access support, when enabled, FLEXSPI return before waiting for command execution finished.
    pub enable_ahb_bufferable: bool,
    /// Enable AHB bus cachable read access support.
    pub enable_ahb_cachable: bool,
}

#[derive(Clone, Copy, Debug)]
/// FlexSPI configuration structure
pub struct FlexspiConfig {
    /// Sample Clock source selection for Flash Reading.
    pub rx_sample_clock: FlexspiReadSampleClock,
    /// Enable/disable SCK output free-running.
    pub enable_sck_free_running: bool,
    /// Enable/disable combining PORT A and B Data Pins (SIOA[3:0] and SIOB[3:0]) to support Flash Octal mode.
    pub enable_combination: bool,
    /// Enable/disable doze mode support.
    pub enable_doze: bool,
    /// Enable/disable divide by 2 of the clock for half speed commands.
    pub enable_half_speed_access: bool,
    /// Enable/disable SCKB pad use as SCKA differential clock output, when enable, Port B flash access is not available.
    pub enable_sck_b_diff_opt: bool,
    /// Enable/disable same configuration for all connected devices when enabled, same configuration in FLASHA1CRx is applied to all.
    pub enable_same_config_for_all: bool,
    /// Timeout wait cycle for command sequence execution, timeout after ahbGrantTimeoutCyle*1024 serial root clock cycles.
    pub seq_timeout_cycle: u16,
    /// Timeout wait cycle for IP command grant, timeout after ipGrantTimeoutCycle*1024 AHB clock cycles.
    pub ip_grant_timeout_cycle: u8,
    /// FLEXSPI IP transmit watermark value.
    pub tx_watermark: usize,
    /// FLEXSPI receive watermark value.
    pub rx_watermark: usize,
    /// AHB configuration
    pub ahb_config: AhbConfig,
}

mod sealed {
    /// simply seal a trait
    pub trait Sealed {}
}

impl<T> sealed::Sealed for T {}

struct Info {
    regs: &'static crate::pac::flexspi::RegisterBlock,
}

trait SealedInstance {
    fn info() -> Info;
}
/// Instance trait to be used for instanciating for FlexSPI HW instance
#[allow(private_bounds)]
pub trait Instance: SealedInstance + Peripheral<P = Self> + 'static + Send {
    /// Interrupt for this SPI instance.
    type Interrupt: interrupt::typelevel::Interrupt;
}

impl SealedInstance for crate::peripherals::FLEXSPI {
    fn info() -> Info {
        Info {
            regs: unsafe { &*crate::pac::Flexspi::ptr() },
        }
    }
}

impl Instance for crate::peripherals::FLEXSPI {
    type Interrupt = crate::interrupt::typelevel::FLEXSPI;
}
/// Driver mode.
#[allow(private_bounds)]
pub trait Mode: sealed::Sealed {}

/// Blocking mode.
pub struct Blocking;
impl Mode for Blocking {}

/// Async mode.
pub struct Async;
impl Mode for Async {}

#[allow(private_interfaces)]
/// FlexSPI Configuration Manager Port
pub struct FlexSpiConfigurationPort {
    /// Bus Width
    _bus_width: FlexSpiBusWidth,
    /// Flash Port
    flash_port: FlexSpiFlashPort,
    /// Device Instance
    device_instance: FlexSpiFlashPortDeviceInstance,
    /// FlexSPI HW Info Object
    info: Info,
}

/// FlexSPI instance
pub struct FlexspiNorStorageBus<M: Mode> {
    /// FlexSPI HW Info Object
    info: Info,
    /// RX FIFO watermark level
    rx_watermark: usize,
    /// TX FIFO Watermark Level
    _tx_watermark: u8,
    /// Mode Phantom object
    _mode: core::marker::PhantomData<M>,
    /// FlexSPI Configuration Port
    pub configport: FlexSpiConfigurationPort,
}
struct LutInstrCookie {
    seq_num: usize,
    instr_num: usize,
}

impl LutInstrCookie {
    fn next_instruction(&mut self) {
        if self.instr_num == 1 {
            self.seq_num += 1;
            self.instr_num = 0;
        } else {
            self.instr_num += 1;
        }
    }
}

#[derive(Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[allow(non_snake_case)]
/// FlexSPI self.flexspi_ref specific errors
/// This enum provides verbose error messages for FlexSPI self.flexspi_ref specific errors
pub enum FlexSpiError {
    /// Flash command grant error
    CmdGrantErr {
        /// AHB read command error
        AhbReadCmdErr: bool,
        /// AHB write command error
        AhbWriteCmdErr: bool,
        /// IP command error
        IpCmdErr: bool,
    }, // INTR[AHBCMDGE] = 1 / INTR[IPCMDGE] = 1
    /// Flash command check error
    CmdCheckErr {
        /// AHB read command error
        AhbReadCmdErr: bool,
        /// AHB write command error
        AhbWriteCmdErr: bool,
        /// IP command error
        IpCmdErr: bool,
    }, // INTR[AHBCMDERR] = 1/ INTR[IPCMDERR] = 1
    /// Flash command execution error
    CmdExecErr {
        /// AHB read command error
        AhbReadCmdErr: bool,
        /// AHB write command error
        AhbWriteCmdErr: bool,
        /// IP command error
        IpCmdErr: bool,
    }, // INTR[AHBCMDERR] = 1/ INTR[SEQTIMEOUT] = 1/ INTR[IPCMDERR] = 1
    /// AHB bus timeout error
    AhbBusTimeout {
        /// AHB read command error
        AhbReadCmdErr: bool, // INTR[AHBBUSTIMEO UT] = 1
        /// AHB write command error
        AhbWriteCmdErr: bool, // INTR[AHBBUSTIMEO UT] = 1
    },
    /// Data learning failed
    DataLearningFailed, // INTR[DATALEARNFAIL] = 1
}

impl FlexSpiError {
    /// Get the description of the error
    pub fn describe(&self) -> &str {
        match self {
            FlexSpiError::CmdGrantErr {
                AhbReadCmdErr,
                AhbWriteCmdErr,
                IpCmdErr,
            } => {
                if *AhbReadCmdErr {
                    "AHB bus error response for Read Command. Command grant timeout"
                } else if *AhbWriteCmdErr {
                    "AHB bus error response for Write Command. Command grant timeout"
                } else if *IpCmdErr {
                    "IP command grant timeout. Command grant timeout"
                } else {
                    "Unknown Flash command grant error"
                }
            }
            FlexSpiError::CmdCheckErr {
                AhbReadCmdErr,
                AhbWriteCmdErr,
                IpCmdErr,
            } => {
                if *AhbWriteCmdErr {
                    "Command is not executed when error detected in command check. Following are the possible reasons:
                    - AHB write command with JMP_ON_CS instruction used in the sequence
                    - There is unknown instruction opcode in the sequence.
                    - Instruction DUMMY_SDR/DUMMY_RWDS_SDR used in DDR sequence.
                    - Instruction DUMMY_DDR/DUMMY_RWDS_DDR used in SDR sequence."
                } else if *AhbReadCmdErr {
                    "Command is not executed when error detected in command check. Following are the possible reasons:
                    - There is unknown instruction opcode in the sequence
                    - Instruction DUMMY_SDR/DUMMY_RWDS_SDR used in DDR sequence.
                    - Instruction DUMMY_DDR/DUMMY_RWDS_DDR used in SDR sequence."
                } else if *IpCmdErr {
                    "Command is not executed when error detected in command check. Following are the possible reasons:
                    - IP command with JMP_ON_CS instruction used in the sequence
                    - There is unknown instruction opcode in the sequence.
                    - Instruction DUMMY_SDR/DUMMY_RWDS_SDRused in DDR sequence
                    - Instruction DUMMY_DDR/DUMMY_RWDS_DDR used in SDR sequence
                    - Flash boundary across"
                } else {
                    "Unknown Flash command check error"
                }
            }
            FlexSpiError::CmdExecErr {
                AhbReadCmdErr,
                AhbWriteCmdErr,
                IpCmdErr,
            } => {
                if *AhbWriteCmdErr {
                    "There will be AHB bus error response except the following cases: 
                        - AHB write command is triggered by flush (INCR burst ended with AHB_TX_BUF not empty)
                        - AHB bufferable write access and bufferable enabled (AHBCR[BUFFERABLEEN]=0x1)
                    Following are possible reasons for this error - 
                        - Command timeout during execution"
                } else if *AhbReadCmdErr {
                    "There will be AHB bus error response. Following are possible reasons for this error - 
                        - Command timeout during execution"
                } else if *IpCmdErr {
                    "Following are possible reasons for this error - 
                        - Command timeout during execution"
                } else {
                    "Unknown Flash command execution error"
                }
            }
            FlexSpiError::AhbBusTimeout {
                AhbReadCmdErr,
                AhbWriteCmdErr,
            } => {
                if *AhbReadCmdErr || *AhbWriteCmdErr {
                    "There will be AHB bus error response. Following are possible reasons for this error - 
                        - AHB bus timeout (no bus ready return)"
                } else {
                    "Unknown AHB bus timeout error"
                }
            }
            FlexSpiError::DataLearningFailed => "Data learning failed",
        }
    }
}

// impl AsyncNorStorageBusDriver for FlexspiNorStorageBus<Async> {
//     async fn send_command(&mut self, write_buf: Option<&[u8]>) -> Result<(), impl NorStorageBusError> {
//         //poll_fn(|cx| Poll::Pending).await
//         // Poll::Rea
//     }
// }

impl BlockingNorStorageBusDriver for FlexspiNorStorageBus<Blocking> {
    fn send_command(
        &mut self,
        cmd: NorStorageCmd,
        read_buf: Option<&mut [u8]>,
        write_buf: Option<&[u8]>,
    ) -> Result<(), StorageBusError> {
        self.setup_ip_transfer(2, cmd.addr, cmd.data_bytes);
        self.program_lut(&cmd, 2);
        self.execute_ip_cmd();
        self.wait_for_cmd_completion();

        info!("IP command done");

        info!("Reading INTR = {:08X}", self.info.regs.intr().read().bits());
        info!("Reading Status 0 = {:08X}", self.info.regs.sts0().read().bits());
        info!("Reading Status 1 = {:08X}", self.info.regs.sts1().read().bits());

        if self.is_error_state() {
            return Err(StorageBusError::StorageBusInternalError);
        }

        if let Some(data_cmd) = cmd.cmdtype {
            // Its a data transfer command
            match data_cmd {
                NorStorageCmdType::Read => {
                    let buffer = read_buf.unwrap();
                    self.read_cmd_data(cmd.data_bytes.unwrap() as usize, buffer);
                }
                NorStorageCmdType::Write => {
                    let buffer = write_buf.unwrap();
                    self.write_cmd_data(buffer.len(), buffer);
                }
            }
        }
        Ok(())
    }
}

impl<M: Mode> FlexspiNorStorageBus<M> {
    fn is_error_state(&self) -> bool {
        //TODO - Implement this function
        false
    }

    fn write_even_instr(&self, seq_id: usize, opcode: FlexSpiLutOpcode, operand: u8, bus_width: u8) {
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.opcode0().bits(opcode as u8) });
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.num_pads0().bits(bus_width) });
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.operand0().bits(operand) });
    }

    fn write_odd_instr(&self, seq_id: usize, opcode: FlexSpiLutOpcode, operand: u8, bus_width: u8) {
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.opcode1().bits(opcode as u8) });
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.num_pads1().bits(bus_width) });
        self.info
            .regs
            .lut(seq_id)
            .modify(|_, w| unsafe { w.operand1().bits(operand) });
    }

    fn program_cmd_instruction(&self, cmd: &NorStorageCmd, cookie: &mut LutInstrCookie) {
        let seq_id = cookie.seq_num as usize;
        let mut cmd_mode: FlexSpiLutOpcode = CMD_DDR;

        if cmd.mode == NorStorageCmdMode::SDR {
            cmd_mode = CMD_SDR;
        }
        let bus_width = match cmd.bus_width {
            NorStorageBusWidth::Single => 0,
            NorStorageBusWidth::Dual => 1,
            NorStorageBusWidth::Quad => 2,
            NorStorageBusWidth::Octal => 3,
        };

        self.write_even_instr(seq_id, cmd_mode, cmd.cmd_lb, bus_width);

        cookie.next_instruction();

        if cmd.cmd_ub.is_some() {
            self.write_odd_instr(seq_id, cmd_mode, cmd.cmd_ub.unwrap(), bus_width);
            cookie.next_instruction();
        }
    }

    fn program_addr_instruction(&self, cmd: &NorStorageCmd, cookie: &mut LutInstrCookie) {
        let seq_id = cookie.seq_num as usize;
        let mut cmd_mode: FlexSpiLutOpcode = RADDR_DDR;

        if cmd.mode == NorStorageCmdMode::SDR {
            cmd_mode = RADDR_SDR;
        }
        let bus_width = match cmd.bus_width {
            NorStorageBusWidth::Single => 0,
            NorStorageBusWidth::Dual => 1,
            NorStorageBusWidth::Quad => 2,
            NorStorageBusWidth::Octal => 3,
        };
        if cookie.instr_num == 0 {
            self.write_even_instr(seq_id, cmd_mode, cmd.addr_width.unwrap(), bus_width);
        } else {
            self.write_odd_instr(seq_id, cmd_mode, cmd.addr_width.unwrap(), bus_width);
        }
        cookie.next_instruction();
    }

    fn program_dummy_instruction(&self, cmd: &NorStorageCmd, cookie: &mut LutInstrCookie) {
        let seq_id = cookie.seq_num as usize;
        let mut cmd_mode: FlexSpiLutOpcode = DUMMY_DDR;

        if cmd.mode == NorStorageCmdMode::SDR {
            cmd_mode = DUMMY_SDR;
        }
        let bus_width = match cmd.bus_width {
            NorStorageBusWidth::Single => 0,
            NorStorageBusWidth::Dual => 1,
            NorStorageBusWidth::Quad => 2,
            NorStorageBusWidth::Octal => 3,
        };
        let mut dummy_val: u8;

        match cmd.dummy {
            DummyCycles::Bytes(dummy_bytes) => {
                dummy_val = dummy_bytes;
            }
            DummyCycles::Clocks(dummy_cycles) => {
                dummy_val = dummy_cycles;
            }
        }
        if cookie.instr_num == 0 {
            self.write_even_instr(seq_id, cmd_mode, dummy_val, bus_width);
        } else {
            self.write_odd_instr(seq_id, cmd_mode, dummy_val, bus_width);
        }
        cookie.next_instruction();
    }

    fn program_read_data_instruction(&self, cmd: &NorStorageCmd, cookie: &mut LutInstrCookie, data_length: u8) {
        let seq_id = cookie.seq_num as usize;
        let mut cmd_mode: FlexSpiLutOpcode = READ_DDR;

        if cmd.mode == NorStorageCmdMode::SDR {
            cmd_mode = READ_SDR;
        }
        let bus_width = match cmd.bus_width {
            NorStorageBusWidth::Single => 0,
            NorStorageBusWidth::Dual => 1,
            NorStorageBusWidth::Quad => 2,
            NorStorageBusWidth::Octal => 3,
        };

        if cookie.instr_num == 0 {
            self.write_even_instr(seq_id, cmd_mode, data_length, bus_width);
        } else {
            self.write_odd_instr(seq_id, cmd_mode, data_length, bus_width);
        }
        cookie.next_instruction();
    }

    fn program_write_data_instruction(&self, cmd: &NorStorageCmd, cookie: &mut LutInstrCookie, data_length: u8) {
        let seq_id = cookie.seq_num as usize;
        let mut cmd_mode: FlexSpiLutOpcode = WRITE_DDR;

        if cmd.mode == NorStorageCmdMode::SDR {
            cmd_mode = WRITE_SDR;
        }
        let bus_width = match cmd.bus_width {
            NorStorageBusWidth::Single => 0,
            NorStorageBusWidth::Dual => 1,
            NorStorageBusWidth::Quad => 2,
            NorStorageBusWidth::Octal => 3,
        };
        if cookie.instr_num == 0 {
            self.write_even_instr(seq_id, cmd_mode, data_length, bus_width);
        } else {
            self.write_odd_instr(seq_id, cmd_mode, data_length, bus_width);
        }
        cookie.next_instruction();
    }

    fn program_stop_instruction(&self, cookie: &mut LutInstrCookie) {
        let seq_id = cookie.seq_num as usize;
        let cmd_mode: FlexSpiLutOpcode = STOP;

        if cookie.instr_num == 0 {
            self.write_even_instr(seq_id, cmd_mode, 0, 0);
        } else {
            self.write_odd_instr(seq_id, cmd_mode, 0, 0);
        }
        cookie.next_instruction();
    }

    fn program_lut(&self, cmd: &NorStorageCmd, seq_id: usize) {
        let mut cookie = LutInstrCookie {
            seq_num: seq_id * 4,
            instr_num: 0,
        };

        // Unlock LUT
        self.info
            .regs
            .lutkey()
            .modify(|_, w| unsafe { w.key().bits(0x5AF05AF0) });
        self.info.regs.lutcr().write(|w| w.unlock().set_bit());

        self.program_cmd_instruction(cmd, &mut cookie);

        if cmd.addr_width.is_some() {
            self.program_addr_instruction(cmd, &mut cookie);
        }

        self.program_dummy_instruction(cmd, &mut cookie);

        self.program_stop_instruction(&mut cookie);

        if let Some(mut data_length) = cmd.data_bytes {
            if let Some(transfertype) = cmd.cmdtype {
                match transfertype {
                    NorStorageCmdType::Read => {
                        if data_length >= 256 {
                            loop {
                                if data_length >= 256 {
                                    self.program_read_data_instruction(cmd, &mut cookie, 255_u8);
                                } else {
                                    self.program_read_data_instruction(cmd, &mut cookie, data_length as u8);
                                    break;
                                }
                                data_length -= 256;
                            }
                        } else {
                            self.program_read_data_instruction(cmd, &mut cookie, data_length as u8);
                        }
                    }
                    NorStorageCmdType::Write => {
                        if data_length >= 256 {
                            loop {
                                if data_length >= 256 {
                                    self.program_write_data_instruction(cmd, &mut cookie, 255_u8);
                                } else {
                                    self.program_write_data_instruction(cmd, &mut cookie, data_length as u8);
                                    break;
                                }
                                data_length -= 256;
                            }
                        } else {
                            self.program_write_data_instruction(cmd, &mut cookie, data_length as u8);
                        }
                    }
                }
            }
        }

        info!("lut 8 = {:08X}", self.info.regs.lut(8).read().bits());
        info!("lut 9 = {:08X}", self.info.regs.lut(9).read().bits());
        info!("lut 10 = {:08X}", self.info.regs.lut(10).read().bits());
        info!("lut 11 = {:08X}", self.info.regs.lut(11).read().bits());

        // Lock LUT
        self.info.regs.lutkey().write(|w| unsafe { w.key().bits(0x5AF05AF0) });
        self.info.regs.lutcr().write(|w| w.lock().set_bit());
    }
}

impl FlexspiNorStorageBus<Blocking> {
    fn setup_ip_transfer(&mut self, seq_id: u8, addr: Option<u32>, size: Option<u32>) {
        match addr {
            Some(addr) => {
                self.info.regs.ipcr0().modify(|_, w| unsafe { w.sfar().bits(addr) });
            }

            None => {
                self.info.regs.ipcr0().modify(|_, w| unsafe { w.sfar().bits(0) });
            }
        }
        // Clear the sequence ID
        self.info.regs.ipcr1().write(|w| unsafe { w.iseqid().bits(0) });
        // Set the Command sequence ID
        self.info.regs.ipcr1().write(|w| unsafe { w.iseqid().bits(seq_id) });

        // Reset the sequence pointer
        self.info.regs.flshcr2(0).write(|w| w.clrinstrptr().set_bit());
        self.info.regs.flshcr2(1).write(|w| w.clrinstrptr().set_bit());
        self.info.regs.flshcr2(2).write(|w| w.clrinstrptr().set_bit());
        self.info.regs.flshcr2(3).write(|w| w.clrinstrptr().set_bit());

        // Disable DMA for TX and RX
        self.info.regs.iptxfcr().write(|w| w.txdmaen().clear_bit());
        self.info.regs.iprxfcr().write(|w| w.rxdmaen().clear_bit());

        // TODO: Set Tx and Rx watermark

        // Reset RX and TX FIFO
        self.info.regs.iprxfcr().write(|w| w.clriprxf().set_bit());
        self.info.regs.iptxfcr().write(|w| w.clriptxf().set_bit());
    }

    fn execute_ip_cmd(&mut self) {
        self.info.regs.ipcmd().write(|w| w.trg().set_bit());
    }

    fn wait_for_cmd_completion(&mut self) {
        while self.info.regs.intr().read().ipcmddone().bit_is_clear() {}
    }

    fn read_cmd_data(&mut self, mut size: usize, read_data: &mut [u8]) {
        loop {
            // Watermark is always >= 8 bytes. So for any data < 8, read FILL level to confirm
            // data arrival
            info!("Size: {}", size);
            if size <= self.rx_watermark {
                // Wait for data to reach
                while (self.info.regs.iprxfsts().read().fill().bits() * 8) < size as u8 {}

                info!("Reading INTR = {:08X}", self.info.regs.intr().read().bits());

                let mut temp = self.info.regs.rfdr(0).read().bits();
                read_data[0] = temp as u8;
                read_data[1] = (temp >> 8) as u8;
                read_data[2] = (temp >> 16) as u8;
                //read_data[3] = (temp >> 24) as u8;
                size = 0;
                if size > 0 {
                    temp = self.info.regs.rfdr(1).read().bits();
                    read_data[4] = temp as u8;
                    read_data[5] = (temp >> 8) as u8;
                    read_data[6] = (temp >> 16) as u8;
                    read_data[7] = (temp >> 24) as u8;
                    size -= 4;
                }
                // Clear out the water mark level data
                self.info.regs.intr().write(|w| w.iprxwa().clear_bit_by_one());
                size = 0;
            } else {
                // Wait for data to reach watermark level
                while self.info.regs.intr().read().iprxwa().bit_is_clear() {}
                // Read the watermark level data
                let num_fifo_slot = self.rx_watermark / 4;
                let mut data_cnt = 0;
                for i in 0..num_fifo_slot {
                    //read_data[i as usize] = self.info.regs.rfdr(i as usize).read().bits();
                    data_cnt += 1;
                }
                // Read the remaining data
                //read_data[data_cnt as usize] = self.info.regs.rfdr(num_fifo_slot as usize).read().bits();
                // Clear out the water mark level data
                self.info.regs.intr().modify(|_, w| w.iprxwa().clear_bit_by_one());

                //size -= self.rx_watermark;
            }

            if size == 0 {
                break;
            }
        }
    }

    fn write_cmd_data(&mut self, size: usize, write_data: &[u8]) {
        // TODO
    }
}

// ================================================================================//

/// FlexSPI init API
pub fn init() {
    // TODO - Need to find anything which is required as part of system init
}

impl FlexSpiConfigurationPort {
    /// Initialize FlexSPI
    pub fn configure_flexspi(&mut self, config: &FlexspiConfig) {
        let regs = self.info.regs;

        // Enable Clock and deassert Reset
        enable_and_reset::<peripherals::FLEXSPI>();

        let sysctl_reg = unsafe { &*crate::pac::Sysctl0::ptr() };
        sysctl_reg
            .pdruncfg1_clr()
            .write(|w| w.flexspi_sram_apd().set_bit().flexspi_sram_ppd().set_bit());

        regs.mcr0().modify(|_, w| w.mdis().clear_bit());
        regs.mcr0().modify(|_, w| w.swreset().set_bit());
        while regs.mcr0().read().swreset().bit_is_set() {}

        //• Set MCR0[MDIS] to 0x1 (Make sure self.flexspi_ref is configured in module stop mode)
        regs.mcr0().modify(|_, w| w.mdis().set_bit());

        //• Configure module control registers: MCR0, MCR1, MCR2. (Don't change MCR0[MDIS])
        match config.rx_sample_clock {
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackInternally => {
                regs.mcr0().modify(|_, w| w.rxclksrc().rxclksrc_0());
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackFromDqsPad => {
                regs.mcr0().modify(|_, w| w.rxclksrc().rxclksrc_1());
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackFromSckPad => {
                regs.mcr0().modify(|_, w| w.rxclksrc().rxclksrc_3());
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkExternalInputFromDqsPad => {
                regs.mcr0().modify(|_, w| w.rxclksrc().rxclksrc_3());
            }
        }
        if config.enable_doze {
            regs.mcr0().modify(|_, w| w.dozeen().set_bit());
        } else {
            regs.mcr0().modify(|_, w| w.dozeen().clear_bit());
        }
        //==============================================================================================
        // These are only for debug purpose. So commenting out for now
        // regs.mcr0()
        //     .modify(|_, w| unsafe { w.ipgrantwait().bits(config.ip_grant_timeout_cycle) });

        // regs.mcr0()
        //     .modify(|_,w| unsafe { w.ahbgrantwait().bits(config.ahb_config.ahb_grant_timeout_cycle) });
        //==============================================================================================

        if config.enable_sck_free_running {
            regs.mcr0().modify(|_, w| w.sckfreerunen().set_bit());
        } else {
            regs.mcr0().modify(|_, w| w.sckfreerunen().clear_bit());
        }

        if config.enable_half_speed_access {
            regs.mcr0().modify(|_, w| w.hsen().set_bit());
        } else {
            regs.mcr0().modify(|_, w| w.hsen().clear_bit());
        }

        regs.mcr1().modify(|_, w| unsafe {
            w.ahbbuswait()
                .bits(config.ahb_config.ahb_bus_timeout_cycle)
                .seqwait()
                .bits(config.seq_timeout_cycle)
        });

        if config.enable_same_config_for_all {
            regs.mcr2().modify(|_, w| w.samedeviceen().set_bit());
        } else {
            regs.mcr2().modify(|_, w| w.samedeviceen().clear_bit());
        }

        regs.mcr2()
            .modify(|_, w| unsafe { w.resumewait().bits(config.ahb_config.resume_wait_cycle) });

        if config.enable_sck_b_diff_opt {
            regs.mcr2().modify(|_, w| w.sckbdiffopt().set_bit());
        } else {
            regs.mcr2().modify(|_, w| w.sckbdiffopt().clear_bit());
        }

        if config.ahb_config.enable_clear_ahb_buffer_opt {
            regs.mcr2().modify(|_, w| w.clrahbbufopt().set_bit());
        } else {
            regs.mcr2().modify(|_, w| w.clrahbbufopt().clear_bit());
        }

        if config.ahb_config.enable_read_address_opt {
            regs.ahbcr().modify(|_, w| w.readaddropt().set_bit());
        } else {
            regs.ahbcr().modify(|_, w| w.readaddropt().clear_bit());
        }

        if config.ahb_config.enable_ahb_prefetch {
            regs.ahbcr().modify(|_, w| w.prefetchen().set_bit());
        } else {
            regs.ahbcr().modify(|_, w| w.prefetchen().clear_bit());
        }

        if config.ahb_config.enable_ahb_bufferable {
            regs.ahbcr().modify(|_, w| w.bufferableen().set_bit());
        } else {
            regs.ahbcr().modify(|_, w| w.bufferableen().clear_bit());
        }

        if config.ahb_config.enable_ahb_cachable {
            regs.ahbcr().modify(|_, w| w.cachableen().set_bit());
        } else {
            regs.ahbcr().modify(|_, w| w.cachableen().clear_bit());
        }

        regs.ahbrxbuf0cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf1cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf2cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf3cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf4cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf5cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf6cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        regs.ahbrxbuf7cr0().modify(|_, w| unsafe {
            w.mstrid()
                .bits(0)
                .prefetchen()
                .set_bit()
                .bufsz()
                .bits(256)
                .priority()
                .bits(0)
        });

        // • Initialize Flash control registers (FLSHxCR0,FLSHxCR1,FLSHxCR2)
        match self.flash_port {
            FlexSpiFlashPort::PortA => match self.device_instance {
                FlexSpiFlashPortDeviceInstance::DeviceInstance0 => {
                    regs.flsha1cr0().modify(|_, w| unsafe { w.flshsz().bits(0) });
                }
                FlexSpiFlashPortDeviceInstance::DeviceInstance1 => {
                    regs.flsha2cr0().modify(|_, w| unsafe { w.flshsz().bits(0) });
                }
            },
            FlexSpiFlashPort::PortB => match self.device_instance {
                FlexSpiFlashPortDeviceInstance::DeviceInstance0 => {
                    regs.flshb1cr0().modify(|_, w| unsafe { w.flshsz().bits(0) });
                }
                FlexSpiFlashPortDeviceInstance::DeviceInstance1 => {
                    regs.flshb2cr0().modify(|_, w| unsafe { w.flshsz().bits(0) });
                }
            },
        }

        regs.iprxfcr().modify(|_, w| unsafe { w.rxwmrk().bits(0) });
        regs.iptxfcr().modify(|_, w| unsafe { w.txwmrk().bits(0) });
    }

    /// Configure the flash self.flexspi_ref based on the external flash device
    pub fn configure_flexspi_device(&self, device_config: &FlexspiDeviceConfig, flexspi_config: &FlexspiConfig) {
        let regs = self.info.regs;
        let flash_size = device_config.flash_size_kb;

        while regs.sts0().read().arbidle().bit_is_clear() || regs.sts0().read().seqidle().bit_is_clear() {}

        let dll_val = Self::calc_dll_value(&device_config, &flexspi_config);

        if device_config.enable_write_mask {
            regs.flshcr4().modify(|_, w| w.wmopt1().wmopt1_1());
        } else {
            regs.flshcr4().modify(|_, w| w.wmopt1().wmopt1_0());
        }

        match self.flash_port {
            FlexSpiFlashPort::PortA => {
                regs.dllcr(0).modify(|_, w| unsafe { w.bits(dll_val) });
                if device_config.enable_write_mask {
                    regs.flshcr4().modify(|_, w| w.wmena().wmena_1());
                } else {
                    regs.flshcr4().modify(|_, w| w.wmena().wmena_0());
                }
                match self.device_instance {
                    FlexSpiFlashPortDeviceInstance::DeviceInstance0 => {
                        regs.flsha1cr0().modify(|_, w| unsafe { w.flshsz().bits(flash_size) });
                        regs.flshcr1a1().modify(|_, w| unsafe {
                            w.csinterval()
                                .bits(device_config.cs_interval)
                                .tcsh()
                                .bits(device_config.cs_hold_time)
                                .tcss()
                                .bits(device_config.cs_setup_time)
                                .cas()
                                .bits(device_config.columnspace)
                                .wa()
                                .bit(device_config.enable_word_address)
                        });
                        match device_config.cs_interval_unit {
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit256Cycle => {
                                regs.flshcr1a1().modify(|_, w| w.csintervalunit().csintervalunit_1());
                            }
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit1Cycle => {
                                regs.flshcr1a1().modify(|_, w| w.csintervalunit().csintervalunit_0());
                            }
                        }
                        match device_config.ahb_write_wait_unit {
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_0());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_1());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_2());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit128ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_3());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit512ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_4());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2048ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_5());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8192ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_6());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32768ahbCycle => {
                                regs.flshcr2a1().modify(|_, w| w.awrwaitunit().awrwaitunit_7());
                            }
                        }

                        if device_config.ard_seq_number > 0 {
                            regs.flshcr2a1().modify(|_, w| unsafe {
                                w.ardseqnum()
                                    .bits(device_config.ard_seq_number - 1)
                                    .ardseqid()
                                    .bits(device_config.ard_seq_index)
                            });
                        }
                    }

                    FlexSpiFlashPortDeviceInstance::DeviceInstance1 => {
                        regs.flsha2cr0().modify(|_, w| unsafe { w.flshsz().bits(flash_size) });
                        regs.flshcr1a2().modify(|_, w| unsafe {
                            w.csinterval()
                                .bits(device_config.cs_interval)
                                .tcsh()
                                .bits(device_config.cs_hold_time)
                                .tcss()
                                .bits(device_config.cs_setup_time)
                                .cas()
                                .bits(device_config.columnspace)
                                .wa()
                                .bit(device_config.enable_word_address)
                        });
                        match device_config.cs_interval_unit {
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit256Cycle => {
                                regs.flshcr1a2().modify(|_, w| w.csintervalunit().csintervalunit_1());
                            }
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit1Cycle => {
                                regs.flshcr1a2().modify(|_, w| w.csintervalunit().csintervalunit_0());
                            }
                        }
                        match device_config.ahb_write_wait_unit {
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_0());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_1());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_2());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit128ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_3());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit512ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_4());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2048ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_5());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8192ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_6());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32768ahbCycle => {
                                regs.flshcr2a2().modify(|_, w| w.awrwaitunit().awrwaitunit_7());
                            }
                        }
                        if device_config.ard_seq_number > 0 {
                            regs.flshcr2a2().modify(|_, w| unsafe {
                                w.ardseqnum()
                                    .bits(device_config.ard_seq_number - 1)
                                    .ardseqid()
                                    .bits(device_config.ard_seq_index)
                            });
                        }
                    }
                }
            }
            FlexSpiFlashPort::PortB => {
                regs.dllcr(1).modify(|_, w| unsafe { w.bits(dll_val) });
                if device_config.enable_write_mask {
                    regs.flshcr4().modify(|_, w| w.wmenb().wmenb_1());
                } else {
                    regs.flshcr4().modify(|_, w| w.wmenb().wmenb_0());
                }
                match self.device_instance {
                    FlexSpiFlashPortDeviceInstance::DeviceInstance0 => {
                        regs.flshb1cr0().modify(|_, w| unsafe { w.flshsz().bits(flash_size) });
                        regs.flshcr1b1().modify(|_, w| unsafe {
                            w.csinterval()
                                .bits(device_config.cs_interval)
                                .tcsh()
                                .bits(device_config.cs_hold_time)
                                .tcss()
                                .bits(device_config.cs_setup_time)
                                .cas()
                                .bits(device_config.columnspace)
                                .wa()
                                .bit(device_config.enable_word_address)
                        });
                        match device_config.cs_interval_unit {
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit256Cycle => {
                                regs.flshcr1b1().modify(|_, w| w.csintervalunit().csintervalunit_1());
                            }
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit1Cycle => {
                                regs.flshcr1b1().modify(|_, w| w.csintervalunit().csintervalunit_0());
                            }
                        }
                        match device_config.ahb_write_wait_unit {
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_0());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_1());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_2());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit128ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_3());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit512ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_4());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2048ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_5());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8192ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_6());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32768ahbCycle => {
                                regs.flshcr2b1().modify(|_, w| w.awrwaitunit().awrwaitunit_7());
                            }
                        }
                        if device_config.ard_seq_number > 0 {
                            regs.flshcr2b1().modify(|_, w| unsafe {
                                w.ardseqnum()
                                    .bits(device_config.ard_seq_number - 1)
                                    .ardseqid()
                                    .bits(device_config.ard_seq_index)
                            });
                        }
                    }
                    FlexSpiFlashPortDeviceInstance::DeviceInstance1 => {
                        regs.flshb2cr0().modify(|_, w| unsafe { w.flshsz().bits(flash_size) });
                        regs.flshcr1b2().modify(|_, w| unsafe {
                            w.csinterval()
                                .bits(device_config.cs_interval)
                                .tcsh()
                                .bits(device_config.cs_hold_time)
                                .tcss()
                                .bits(device_config.cs_setup_time)
                                .cas()
                                .bits(device_config.columnspace)
                                .wa()
                                .bit(device_config.enable_word_address)
                        });
                        match device_config.cs_interval_unit {
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit256Cycle => {
                                regs.flshcr1b2().modify(|_, w| w.csintervalunit().csintervalunit_1());
                            }
                            FlexspiCsIntervalCycleUnit::CsIntervalUnit1Cycle => {
                                regs.flshcr1b2().modify(|_, w| w.csintervalunit().csintervalunit_0());
                            }
                        }
                        match device_config.ahb_write_wait_unit {
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_0());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_1());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_2());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit128ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_3());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit512ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_4());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit2048ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_5());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit8192ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_6());
                            }
                            FlexspiAhbWriteWaitUnit::FlexspiAhbWriteWaitUnit32768ahbCycle => {
                                regs.flshcr2b2().modify(|_, w| w.awrwaitunit().awrwaitunit_7());
                            }
                        }
                        if device_config.ard_seq_number > 0 {
                            regs.flshcr2b2().modify(|_, w| unsafe {
                                w.ardseqnum()
                                    .bits(device_config.ard_seq_number - 1)
                                    .ardseqid()
                                    .bits(device_config.ard_seq_index)
                            });
                        }
                    }
                }
            }
        }

        // Enable the module
        regs.mcr0().modify(|_, w| w.mdis().clear_bit());

        //Errata ERR011377 - need to delay at least 100 NOPs to ensure the DLL is locked.
        match self.flash_port {
            FlexSpiFlashPort::PortA => {
                while regs.sts2().read().aslvlock().bit_is_clear() && regs.sts2().read().areflock().bit_is_clear() {
                    // Wait for DLL lock
                }

                for i in 0..100 {
                    asm::nop();
                }
            }
            FlexSpiFlashPort::PortB => {
                while regs.sts2().read().bslvlock().bit_is_clear() && regs.sts2().read().breflock().bit_is_clear() {
                    // Wait for DLL lock
                }

                for i in 0..100 {
                    asm::nop();
                }
            }
        }
    }

    fn calc_dll_value(device_config: &FlexspiDeviceConfig, flexspi_config: &FlexspiConfig) -> u32 {
        let mut is_unified_config = true;
        let mut flexspi_dll_value = 0u32;
        let mut dll_value = 0u32;
        let mut temp = 0u32;

        let rx_sample_clock = flexspi_config.rx_sample_clock;
        match rx_sample_clock {
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackInternally => {
                is_unified_config = true;
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackFromDqsPad => {
                is_unified_config = true;
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkLoopbackFromSckPad => {
                is_unified_config = true;
            }
            FlexspiReadSampleClock::FlexspiReadSampleClkExternalInputFromDqsPad => {
                is_unified_config = device_config.is_sck2_enabled;
            }
        }

        if is_unified_config {
            flexspi_dll_value = 0x100; /* 1 fixed delay cells in DLL delay chain) */
        } else if (device_config.flexspi_root_clk >= 100000000) {
            /* DLLEN = 1, SLVDLYTARGET = 0xF, */
            flexspi_dll_value = 0x1 | (0xF << 3);
        } else {
            temp = (device_config.data_valid_time) as u32 * 1000; /* Convert data valid time in ns to ps. */
            dll_value = temp / 75;
            if (dll_value * 75 < temp) {
                dll_value += 1;
            }
            flexspi_dll_value = 0x1 << 8 | (dll_value & 0x78) << 9; // TODO: remove hardcoding
        }
        flexspi_dll_value
    }

    /// Enable or disable clock
    pub fn enable_disable_clock(&self, op: bool) {
        // Enable or disable clock
    }
    /// Enable or disable SRAM
    pub fn enable_disable_sram(&self, op: bool) {
        // Enable or disable SRAM
    }
    /// Reset FlexSPI
    pub fn apply_clear_reset(&self, op: bool) {
        // Reset FlexSPI
    }
    /// Enable Disable FlexSPI module
    pub fn enable_disable_flexspi_module(&self, op: bool) {}
}

impl FlexspiNorStorageBus<Blocking> {
    #[allow(clippy::too_many_arguments)]
    /// Create a new FlexSPI instance in blocking mode with RAM execution
    pub fn new_blocking<T: Instance>(
        _inst: T,
        data0: Option<impl FlexSpiDataPin>,
        data1: Option<impl FlexSpiDataPin>,
        data2: Option<impl FlexSpiDataPin>,
        data3: Option<impl FlexSpiDataPin>,
        data4: Option<impl FlexSpiDataPin>,
        data5: Option<impl FlexSpiDataPin>,
        data6: Option<impl FlexSpiDataPin>,
        data7: Option<impl FlexSpiDataPin>,
        clk: impl FlexSpiClkPin,
        cs: impl FlexSpiCsPin,
        port: FlexSpiFlashPort,
        bus_width: FlexSpiBusWidth,
        dev_instance: FlexSpiFlashPortDeviceInstance,
    ) -> Self {
        if let Some(data0) = data0 {
            data0.config_pin();
        }
        if let Some(data1) = data1 {
            data1.config_pin();
        }
        if let Some(data2) = data2 {
            data2.config_pin();
        }
        if let Some(data3) = data3 {
            data3.config_pin();
        }
        if let Some(data4) = data4 {
            data4.config_pin();
        }
        if let Some(data5) = data5 {
            data5.config_pin();
        }
        if let Some(data6) = data6 {
            data6.config_pin();
        }
        if let Some(data7) = data7 {
            data7.config_pin();
        }

        cs.config_pin();
        clk.config_pin();

        Self {
            info: T::info(),
            rx_watermark: 8,  // 8 bytes
            _tx_watermark: 8, // 8 bytes
            _mode: core::marker::PhantomData,
            configport: FlexSpiConfigurationPort {
                info: T::info(),
                _bus_width: bus_width,
                device_instance: dev_instance,
                flash_port: port,
            },
        }
    }
}

impl FlexspiNorStorageBus<Async> {
    #[allow(clippy::too_many_arguments)]
    /// Create a new FlexSPI instance in blocking mode with RAM execution
    pub fn new_async<T: Instance>(
        _inst: T,
        data0: Option<impl FlexSpiDataPin>,
        data1: Option<impl FlexSpiDataPin>,
        data2: Option<impl FlexSpiDataPin>,
        data3: Option<impl FlexSpiDataPin>,
        data4: Option<impl FlexSpiDataPin>,
        data5: Option<impl FlexSpiDataPin>,
        data6: Option<impl FlexSpiDataPin>,
        data7: Option<impl FlexSpiDataPin>,
        clk: impl FlexSpiClkPin,
        cs: impl FlexSpiCsPin,
        port: FlexSpiFlashPort,
        bus_width: FlexSpiBusWidth,
        dev_instance: FlexSpiFlashPortDeviceInstance,
    ) -> Self {
        if let Some(data0) = data0 {
            data0.config_pin();
        }
        if let Some(data1) = data1 {
            data1.config_pin();
        }
        if let Some(data2) = data2 {
            data2.config_pin();
        }
        if let Some(data3) = data3 {
            data3.config_pin();
        }
        if let Some(data4) = data4 {
            data4.config_pin();
        }
        if let Some(data5) = data5 {
            data5.config_pin();
        }
        if let Some(data6) = data6 {
            data6.config_pin();
        }
        if let Some(data7) = data7 {
            data7.config_pin();
        }

        cs.config_pin();
        clk.config_pin();

        Self {
            info: T::info(),
            rx_watermark: 8,  // 8 bytes
            _tx_watermark: 8, // 8 bytes
            _mode: core::marker::PhantomData,
            configport: FlexSpiConfigurationPort {
                info: T::info(),
                _bus_width: bus_width,
                device_instance: dev_instance,
                flash_port: port,
            },
        }
    }
}

macro_rules! impl_data_pin {
    ($peri:ident, $fn: ident, $invert: ident, $pull: ident) => {
        impl FlexSpiDataPin for crate::peripherals::$peri {
            fn config_pin(&self) {
                self.set_function(crate::iopctl::Function::$fn)
                    .set_pull(crate::iopctl::Pull::None)
                    .set_slew_rate(crate::gpio::SlewRate::Slow)
                    .set_drive_strength(crate::gpio::DriveStrength::Normal)
                    .disable_analog_multiplex()
                    .set_drive_mode(crate::gpio::DriveMode::$pull)
                    .set_input_inverter(crate::gpio::Inverter::$invert);
            }
        }
    };
}

macro_rules! impl_cs_pin {
    ($peri:ident, $fn: ident) => {
        impl FlexSpiCsPin for crate::peripherals::$peri {
            fn config_pin(&self) {
                self.set_function(crate::iopctl::Function::$fn)
                    .set_pull(crate::iopctl::Pull::None)
                    .set_slew_rate(crate::gpio::SlewRate::Standard)
                    .set_drive_strength(crate::gpio::DriveStrength::Normal)
                    .set_drive_mode(crate::gpio::DriveMode::PushPull)
                    .set_input_inverter(crate::gpio::Inverter::Disabled);
            }
        }
    };
}

macro_rules! impl_clk_pin {
    ($peri:ident, $fn: ident) => {
        impl FlexSpiClkPin for crate::peripherals::$peri {
            fn config_pin(&self) {
                self.set_function(crate::iopctl::Function::$fn)
                    .set_pull(crate::iopctl::Pull::None)
                    .enable_input_buffer()
                    .set_slew_rate(crate::gpio::SlewRate::Standard)
                    .set_drive_strength(crate::gpio::DriveStrength::Full)
                    .disable_analog_multiplex()
                    .set_drive_mode(crate::gpio::DriveMode::PushPull)
                    .set_input_inverter(crate::gpio::Inverter::Disabled);
            }
        }
    };
}

/// FlexSPI Data Pins
pub trait FlexSpiDataPin: Pin + sealed::Sealed + crate::Peripheral {
    /// Configure FlexSPI Data Pin
    fn config_pin(&self);
}
/// FlexSPI CS Pin
pub trait FlexSpiCsPin: Pin + sealed::Sealed + crate::Peripheral {
    /// Configure FlexSPI CS Pin
    fn config_pin(&self);
}
/// FlexSPI Clock Pin
pub trait FlexSpiClkPin: Pin + sealed::Sealed + crate::Peripheral {
    /// Configure FlexSPI Clock Pin
    fn config_pin(&self);
}

impl_data_pin!(PIO1_11, F6, Disabled, PushPull); // PortB-DATA0
impl_data_pin!(PIO1_12, F6, Disabled, PushPull); // PortB-DATA1
impl_data_pin!(PIO1_13, F6, Disabled, PushPull); // PortB-DATA2
impl_data_pin!(PIO1_14, F6, Disabled, PushPull); // PortB-DATA3
impl_data_pin!(PIO2_17, F6, Disabled, PushPull); // PortB-DATA4
impl_data_pin!(PIO2_18, F6, Disabled, PushPull); // PortB-DATA5
impl_data_pin!(PIO2_22, F6, Disabled, PushPull); // PortB-DATA6
impl_data_pin!(PIO2_23, F6, Disabled, PushPull); // PortB-DATA7
impl_cs_pin!(PIO2_19, F6); // PortB-CS0
impl_cs_pin!(PIO2_21, F6); // PortB-CS1
impl_clk_pin!(PIO1_29, F5); // PortB-SCLK

impl_cs_pin!(PIO1_19, F1); // PortA-CS0
impl_clk_pin!(PIO1_18, F1); // PortA-SCLK
impl_data_pin!(PIO1_20, F1, Disabled, PushPull); // PortA-DATA0
impl_data_pin!(PIO1_21, F1, Disabled, PushPull); // PortA-DATA1
impl_data_pin!(PIO1_22, F1, Disabled, PushPull); // PortA-DATA2
impl_data_pin!(PIO1_23, F1, Disabled, PushPull); // PortA-DATA3
impl_data_pin!(PIO1_24, F1, Disabled, PushPull); // PortA-DATA4
impl_data_pin!(PIO1_25, F1, Disabled, PushPull); // PortA-DATA5
impl_data_pin!(PIO1_26, F1, Disabled, PushPull); // PortA-DATA6
impl_data_pin!(PIO1_27, F1, Disabled, PushPull); // PortA-DATA7
